naver:
  openapi:
    movieUrl: https://openapi.naver.com/v1/search/movie.json
    bookUrl: https://openapi.naver.com/v1/search/book.json
kakao:
  openapi:
    translateUrl: https://dapi.kakao.com/v2/translation/translate
    contentType: application/x-www-form-urlencoded
rest:
  maxConnTotal: 50
  maxConnPerRoute: 10
  setConnectTimeout: 3000
  readTimeout: 5000

cron:
  expression: 0 0/10 * * * *

spring:
  redis:
    host: localhost
    post: 6379